services:
  postgres:
    image: postgres:latest
    container_name: contact_service_db
    restart: always
    environment:
      POSTGRES_DB: contact_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - contact_service_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - contact_service_net

  contact_service_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contact_service_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contact_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - contact_service_net

volumes:
  contact_service_data:

networks:
  contact_service_net:
